export type EvidenceStatus = "unverified" | "verified";

export interface AssetRecord {
  readonly id: string;
  readonly label: string;
  readonly source: "kronos-cache" | "kronos-client" | "kronos-server";
  readonly evidenceStatus: EvidenceStatus;
  readonly sourceAnchorIds: readonly string[];
  readonly requiredArtifacts: readonly string[];
  readonly acceptanceGate: string;
  readonly notes: string;
}

export const assetCatalog: readonly AssetRecord[] = [
  {
    id: "model-geometry",
    label: "Model geometry exporter",
    source: "kronos-client",
    evidenceStatus: "verified",
    sourceAnchorIds: ["client-model-geometry-contract"],
    requiredArtifacts: [
      "fixtures/assets/models/cache-models.json",
      "fixtures/assets/models/abyssal_tentacle.glb",
      "fixtures/assets/models/armadyl_crossbow.glb",
      "fixtures/assets/models/armadyl_godsword.glb",
      "fixtures/assets/models/kodai_wand.glb",
      "fixtures/assets/models/granite_maul.glb",
      "fixtures/assets/models/ancestral_robes.glb",
      "fixtures/assets/models/bandos_body.glb",
      "fixtures/assets/models/karils_leather.glb",
      "fixtures/render/player-loadouts/kodai-robes.glb",
      "fixtures/render/player-loadouts/acb-hides.glb",
      "fixtures/render/player-loadouts/tentacle-bandos.glb",
      "fixtures/render/player-loadouts/ags-bandos.glb",
      "fixtures/render/player-loadouts/gmaul-bandos.glb",
      "fixtures/render/player-loadouts/kodai-robes.mesh.json",
      "fixtures/render/player-loadouts/acb-hides.mesh.json",
      "fixtures/render/player-loadouts/tentacle-bandos.mesh.json",
      "fixtures/render/player-loadouts/ags-bandos.mesh.json",
      "fixtures/render/player-loadouts/gmaul-bandos.mesh.json"
    ],
    acceptanceGate: "Exporter preserves vertices, faces, colors, textures, alpha, priority, and animation group bindings from the client model contract.",
    notes: "This is the first renderer blocker. Player visuals cannot be real until these cache meshes exist."
  },
  {
    id: "item-equipment-defs",
    label: "Item and equipment definitions",
    source: "kronos-server",
    evidenceStatus: "verified",
    sourceAnchorIds: ["server-item-bonus-contract", "server-equipment-bonus-contract"],
    requiredArtifacts: [
      "fixtures/assets/defs/server-items.json",
      "fixtures/assets/defs/cache-items.json",
      "fixtures/assets/defs/equipment-bonuses.json",
      "fixtures/assets/defs/weapon-types.json",
      "fixtures/assets/defs/nh-loadout-items.json"
    ],
    acceptanceGate: "Definitions include equip slot, bonuses, attack distance, attack ticks, combat style metadata, and item ids used by NH loadouts.",
    notes: "This is what lets the trainer reason about Bandos, hides, robes, melee EV, range EV, and magic EV without hard-coded labels."
  },
  {
    id: "player-kits-and-colors",
    label: "Player kit and body color data",
    source: "kronos-client",
    evidenceStatus: "verified",
    sourceAnchorIds: ["client-player-appearance-packet", "client-player-model-assembly"],
    requiredArtifacts: [
      "fixtures/assets/defs/kits.json",
      "fixtures/assets/defs/body-colors.json"
    ],
    acceptanceGate: "Runtime can rebuild a player's visible body parts and colors from the same appearance fields the client reads.",
    notes: "This prevents a fake mannequin renderer; the player mesh must be composed the Kronos-client way."
  },
  {
    id: "sequence-frames",
    label: "Sequence and frame transforms",
    source: "kronos-client",
    evidenceStatus: "verified",
    sourceAnchorIds: [
      "client-sequence-frame-contract",
      "client-actor-sequence-selection-contract",
      "client-actor-sequence-cycle-contract"
    ],
    requiredArtifacts: [
      "fixtures/assets/animations/sequences.json",
      "fixtures/assets/animations/frames.json",
      "fixtures/render/sequences/idle.json",
      "fixtures/render/sequences/walk.json",
      "fixtures/render/sequences/whip_attack.json",
      "fixtures/render/sequences/godsword_attack.json",
      "fixtures/render/sequences/ags_special.json",
      "fixtures/render/sequences/gmaul_special.json",
      "fixtures/render/sequences/crossbow_attack.json",
      "fixtures/render/sequences/blitz_cast.json",
      "fixtures/render/sequences/barrage_cast.json"
    ],
    acceptanceGate: "Renderer advances OSRS frame lengths and transform labels instead of using invented animation clips.",
    notes: "Needed for visible timing: whips, crossbows, Gmaul specs, spell casts, freezes, idle/walk states, movement-loop sampling, and primary action termination."
  },
  {
    id: "spotanim-projectiles",
    label: "Spot animation and projectile assets",
    source: "kronos-cache",
    evidenceStatus: "verified",
    sourceAnchorIds: [
      "client-projectile-motion-contract",
      "client-projectile-packet-lifecycle",
      "server-projectile-payload-contract",
      "server-targetspell-contract",
      "server-ice-barrage-contract"
    ],
    requiredArtifacts: [
      "fixtures/assets/defs/spotanims.json",
      "fixtures/assets/defs/projectiles.json",
      "fixtures/assets/models/cache-glb-manifest.json",
      "fixtures/render/spotanims/ice_barrage_projectile.glb",
      "fixtures/render/spotanims/ice_barrage_hit.glb",
      "fixtures/render/spotanims/blood_barrage_hit.glb",
      "fixtures/render/spotanims/ice_blitz_cast.glb",
      "fixtures/render/spotanims/ice_blitz_hit.glb",
      "fixtures/render/spotanims/blood_blitz_projectile.glb",
      "fixtures/render/spotanims/blood_blitz_hit.glb",
      "fixtures/render/spotanims/acb_special_projectile.glb",
      "fixtures/render/spotanims/bolt_projectile.glb",
      "fixtures/render/spotanims/dragon_bolt_projectile.glb",
      "fixtures/render/spotanims/ags_special.glb",
      "fixtures/render/spotanims/gmaul_special.glb"
    ],
    acceptanceGate: "Barrage, Blitz, Blood spells, ACB, standard bolt, dragon bolt, and Gmaul spotanim visuals use cache ids plus server payload timing, not approximate particles.",
    notes: "This is the visual layer that makes NH readable rather than just two models swapping gear."
  },
  {
    id: "ui-sprites",
    label: "Cache UI sprites",
    source: "kronos-client",
    evidenceStatus: "verified",
    sourceAnchorIds: [
      "client-actor-overlay-symbol-map",
      "client-head-icon-index-contract",
      "cache-overhead-icon-export-contract",
      "cache-click-cross-sprite-export",
      "client-click-cross-contract",
      "client-context-menu-font-contract",
      "client-context-menu-contract",
      "client-context-menu-sizing-contract",
      "cache-client-font-metrics-export",
      "client-widget-text-draw-contract",
      "client-player-menu-opcode-contract",
      "client-player-context-menu-contract",
      "client-selected-player-target-packet-contract",
      "client-hitsplat-packet-contract",
      "client-hitsplat-definition-contract",
      "client-hitsplat-draw-contract",
      "client-actor-default-height-contract",
      "client-player-model-height-contract",
      "cache-hitsplat-definition-export-contract",
      "client-healthbar-definition-contract",
      "client-healthbar-update-contract",
      "client-healthbar-draw-contract",
      "cache-healthbar-definition-export-contract",
      "client-inventory-slot-layout-contract",
      "client-inventory-widget-item-draw-contract",
      "client-inventory-item-sprite-contract",
      "cache-item-sprite-factory-export-contract",
      "cache-client-widget-layout-export",
      "client-widget-resize-layout-contract",
      "client-widget-position-layout-contract",
      "client-chatbox-widget-contract",
      "client-chatbox-sprite-contract",
      "client-fixed-side-tab-widget-contract",
      "client-interface-tab-order-contract",
      "server-fixed-display-tab-mapping-contract",
      "client-combat-widget-contract",
      "client-combat-specbar-redraw-contract",
      "server-combat-tab-state-contract",
      "server-combat-level-widget-contract",
      "server-combat-varp-contract",
      "client-attack-style-label-contract",
      "client-skills-widget-contract",
      "server-stats-tab-widget-contract",
      "client-skill-level-array-contract",
      "client-enabled-skills-contract",
      "client-skill-sprite-contract",
      "client-equipment-widget-slot-contract",
      "server-equipment-slot-index-contract",
      "server-equipment-tab-item-action-contract",
      "server-equipment-unequip-mutation-contract",
      "client-prayer-widget-order-contract",
      "client-prayer-icon-sprite-contract",
      "cache-prayer-icon-sprite-export-contract",
      "client-spellbook-redraw-layout-contract",
      "client-ancient-spellbook-widget-contract",
      "client-spell-icon-sprite-contract",
      "client-spell-selection-contract",
      "client-selected-spell-object-menu-contract",
      "cache-spellbook-definition-export-contract",
      "client-fixed-viewport-render-contract",
      "client-viewport-resize-contract",
      "client-minimap-default-sprite-load-contract",
      "client-scene-minimap-sprite-build-contract",
      "client-scene-minimap-object-stroke-contract",
      "client-minimap-sprite-mask-row-contract",
      "client-sprite-mask-hit-test-contract",
      "cache-minimap-map-dot-sprite-export",
      "cache-sprite-mask-row-export",
      "cache-arena-object-minimap-metadata-export"
    ],
    requiredArtifacts: [
      "fixtures/assets/defs/client-widgets.json",
      "fixtures/render/sprites/prayer_overheads.png",
      "fixtures/render/sprites/prayer_overheads.json",
      "fixtures/render/sprites/pk_skull.png",
      "fixtures/render/sprites/pk_skull.json",
      "fixtures/assets/defs/overhead-icons.json",
      "fixtures/assets/defs/client-fonts.json",
      "fixtures/render/sprites/client_p11_font.png",
      "fixtures/render/sprites/client_p11_font.json",
      "fixtures/render/sprites/client_p12_font.png",
      "fixtures/render/sprites/client_p12_font.json",
      "fixtures/render/sprites/context_menu_font.png",
      "fixtures/render/sprites/context_menu_font.json",
      "fixtures/render/sprites/click_cross.png",
      "fixtures/render/sprites/click_cross.json",
      "fixtures/render/sprites/client_ui.png",
      "fixtures/render/sprites/client_ui.json",
      "fixtures/render/sprites/compass.png",
      "fixtures/render/sprites/compass.json",
      "fixtures/render/sprites/kronos_fkey_icon.png",
      "fixtures/render/sprites/item_sprites.png",
      "fixtures/render/sprites/item_sprites.json",
      "fixtures/assets/defs/emotes.json",
      "fixtures/render/sprites/emote_icons.png",
      "fixtures/render/sprites/emote_icons.json",
      "fixtures/render/sprites/prayer_icons.png",
      "fixtures/render/sprites/prayer_icons.json",
      "fixtures/assets/defs/spellbooks.json",
      "fixtures/render/sprites/spell_icons.png",
      "fixtures/render/sprites/spell_icons.json",
      "fixtures/render/sprites/minimap_map_dots.png",
      "fixtures/render/sprites/minimap_map_dots.json",
      "fixtures/render/sprites/minimap_map_markers.png",
      "fixtures/render/sprites/minimap_map_markers.json",
      "fixtures/render/sprites/minimap_map_icons.png",
      "fixtures/render/sprites/minimap_map_icons.json",
      "fixtures/render/sprites/minimap_map_scenes.png",
      "fixtures/render/sprites/minimap_map_scenes.json",
      "fixtures/render/sprites/hitsplats.png",
      "fixtures/render/sprites/hitsplats.json",
      "fixtures/render/sprites/hitsplat_digits.png",
      "fixtures/render/sprites/hitsplat_digits.json",
      "fixtures/assets/defs/hitsplats.json",
      "fixtures/assets/defs/healthbars.json",
      "fixtures/render/sprites/health_bars.png",
      "fixtures/render/sprites/health_bars.json"
    ],
    acceptanceGate: "Overheads, hitsplats, actor default/model heights, click crosses, client font metrics/glyphs, minimap scene metadata/sprites, minimap dots/markers, SpriteMask rows, fixed-mode client sprites, chatbox group 162 buttons/actions, DisplayHandler side-panel tab groups, combat tab group 593 with server-backed weapon/style/special state and SpecbarRedraw active/drain behavior, stats tab group 320, equipment tab group 387 item slots, worn-item Remove dispatch/mutation, and utility-button actions, prayer icons/toggle metadata/active background, emote names/icon sprites from clientscript enum ids, standard/ancient/lunar/arceuus spellbook icons/order, and widget layout data are exported from Kronos cache/client contracts.",
    notes: "DOM can host the HUD layer, but visible fixed-mode imagery and slot sizing must come from cache sprites and source widget layout rules."
  },
  {
    id: "inferno-arena-map",
    label: "Inferno arena scene data",
    source: "kronos-cache",
    evidenceStatus: "verified",
    sourceAnchorIds: ["client-model-geometry-contract"],
    requiredArtifacts: [
      "fixtures/render/maps/inferno_arena.glb",
      "fixtures/render/maps/inferno_arena.json",
      "fixtures/render/maps/inferno_arena_objects.glb",
      "fixtures/render/maps/inferno_arena_objects.json",
      "fixtures/assets/defs/arena-objects.json",
      "fixtures/assets/defs/textures.json",
      "fixtures/assets/defs/floors.json",
      "fixtures/render/textures/texture_1.png",
      "fixtures/render/textures/texture_8.png",
      "fixtures/render/textures/texture_60.png"
    ],
    acceptanceGate: "Arena terrain and placed-object metadata come from cache/map extraction, not a drawn grid.",
    notes: "This is what keeps the first screen from becoming another generic 2D mockup. Object animation/impostor handling remains a later pass."
  }
];
